import os
from typing import Any, Dict, List
import logging
from tree.attached_file import AttachedFile
import yaml

class PromptBuilder:
    def __init__(
        self
    ):
        self.logger = logging.getLogger(__name__)
        self.is_prod_mode = os.getenv("DEV_MODE", "false").lower() == "false"
        self.attached_files: List[AttachedFile] = []

    def attach_files(self, files: list):
        """Attach files to the prompt for additional context."""
        self.attached_files.extend(files)

    def attach_file(self, file: AttachedFile):
        """Attach a file to the prompt for additional context."""
        self.attached_files.append(file)

    def include_attached_files(self, prompt: str) -> str:
        """Include attached files in the prompt for a specific microservice."""
        if self.is_prod_mode and len(self.attached_files) > 0:
            prompt += f"\nAttached files for additional context:\n"
            for file in self.attached_files:
                prompt += f" {file.name}: {file}"
        return prompt

    def _generate_base_prompt(self, services: List[Dict[str, Any]]) -> str:
        """Generate the base prompt for all microservices, providing context for interdependencies."""
        self.logger.info("Generating base prompt for microservices.")

        # Strong role assignment and formatting constraint for small models
        prompt = (
            "You are a strict Kubernetes manifests generator.\n"
            "You only output valid raw Kubernetes YAML manifests starting off from a set of microservices described next.\n"
            "The set of microservices are interrelated and compose an application.\n"
        )

        prompt += "Here is the schema for all microservices in this system:\n\n"
        for index, service in enumerate(services):
            if index > 0:
                prompt += ", "
            prompt += f"{service['name']}"
            # for key, value in service.items():
            #     if key != "attached_files" and key != "manifests":
            #         prompt += f"  {key}: {value}\n"
            # prompt += "\n"
        prompt += ".\n"
        prompt += (
            "Use the above to understand context and infer common configurations "
            "or interdependencies between services, but do not explain them.\n"
        )

        return prompt

    def generate_prompt(self, microservice: Dict[str, Any], microservices: List[Dict[str,Any]]) -> str:
        """Generate a Kubernetes manifest generation prompt for a specific microservice."""
        
        prompt = self._generate_base_prompt(microservices)

        prompt += prompt + "\n"

        prompt += f"Now generate Kubernetes manifests in YAML format for the microservice '{microservice['name']}'.\n\n"

        prompt += "Microservice details:\n"
        
        for key, value in microservice.items():
            if key != "attached_files" and key != "manifests":
                prompt += f"  {key}: {value}\n"


        prompt += "Guidelines:\n"
        prompt += "- Use production-ready Kubernetes best practices.\n"
        prompt += "- Fill in extra fields but keep coherence with the templates provided.\n"
        prompt += "- If needed, add Service, ConfigMap, Secret, or PVC.\n"
        prompt += "- Use labels like `app`, `tier`, `role`, and `environment`.\n"
        prompt += "- Use TODO placeholders for values that cannot be confidently inferred.\n"
        prompt += "- Separate each manifest with '---' if multiple objects are required.\n"
        prompt += "- The result must be directly usable with `kubectl apply -f` or in CI/CD pipelines.\n"
        prompt += "**No other output is allowed. Do not explain, do not reason, do not output markdown or comments.**\n"
        prompt += "**Immediately output only valid Kubernetes YAML for the service.**\n"
        prompt += "Output:\n"

        self.logger.info(
            f"Prompt generated for the {microservice['name']} microservice:\n{prompt}"
        )
        return prompt

    def generate_second_pass_prompt(self) -> str:
        """Generate a second pass prompt to optimize the already generated manifests."""

        prompt = (
            "You are a senior DevOps engineer. Your task is to strictly review and improve Kubernetes manifests.\n\n"
            "Below are a set of synthetic YAML manifests generated by an LLM. Your task is to clean them and output a production ready manifest"
            "Use a YAML format to generate the output."
            "Requirements:\n"
            "1. Enforce production best practices (security, scalability, observability, reliability).\n"
            "2. Ensure all required fields are present (resources, probes, labels, volumes, secrets).\n"
            "3. Ensure manifests coordinate across services (env vars, service names, config refs).\n"
            "4. Output must be valid and directly usable with `kubectl apply -f`.\n\n"
            "Guidelines:\n"
            "- DO NOT guess unknown values. Use '# TODO' where needed.\n"
            "- DO NOT explain anything or include markdown/comments.\n"
            "- DO NOT regenerate unchanged content unless improvement is necessary.\n"
            "- Output ONLY valid raw Kubernetes YAML.\n"
            "- If returning multiple manifests, separate with '---' and prefix with a YAML comment of the object type (e.g., '# Deployment').\n\n"
            "Begin improved YAML output now:\n"
        )
        return prompt